### ISSUE TITLE
Upgrade to support all required architectures?

### ISSUE THREAD

**Issue by eligreg** [fastred/AHKActionSheet#18]
Hi! I'm running in to an error building the app using this repo. I believe it has something to do with missing support for the newest architectures required by iOS8. Attached is a screenshot of the error.

Would you mind updating the repo to support the additional architecture? 

![screen shot 2015-04-01 at 11 24 26 am](https://cloud.githubusercontent.com/assets/2157250/6948376/4d7e3466-d862-11e4-92e8-2c5e08a70394.png)

**Comment by fastred** [comment]
@eligreg What was the issue? Is there something I should fix in AHKActionSheet?

**Comment by eligreg** [comment]
Nothing you need to fix! Turns out it was an issue with the target's build setting. Though I thank you for the response.
