### ISSUE TITLE
Is it possible to disable the cancel button?

### ISSUE THREAD

**Issue by felixchan** [fastred/AHKActionSheet#19]
I've tried setting height to 0 but doesn't seem to work.

Thanks!

**Comment by fastred** [comment]
Thanks for reporting this issue. It should be fixed on `master`.

**Comment by kuldeep13990** [comment]
@felixchan  Comment this line in which cancel button is setup. **[self setUpCancelButton];** and you also need to remove cancel button reference where it use with other. like for (UIView *view in @[self.tableView, self.cancelButton, self.blurredBackgroundView, self.window]) {
            [view removeFromSuperview];
        } remove that self.cancelButton
