### ISSUE TITLE
Image Rendering Mode in cell.imageView

### ISSUE THREAD

**Issue by tomisacat** [fastred/AHKActionSheet#21]
I noticed that you set the cell.imageView.image with origin image renderd in Template, which forced the image the same color with textLabel.textColor. I don't know why does this step?

PS: It's really a good lib, I like it! Appreciate your great work :+1:

**Comment by fastred** [comment]
It was done to match the behavior of Spotify's action sheet. It can be disabled by setting `automaticallyTintButtonImages` value to `@NO`.
