### ISSUE TITLE
Separators do not work in iOS 9

### ISSUE THREAD

**Issue by albertkim** [fastred/AHKActionSheet#28]
They just don't show. ActionSheet.separatorView can be set as any color but they seem to default to the background color. However, they continue to work as intended on iOS 9.

**Comment by fastred** [comment]
Hi! Thanks for reporting this bug.

It seems to work for me on iOS 9, though. I changed `separatorColor` in the example project to red and got:

![simulator screen shot 24-10-2015 22 17 15](https://cloud.githubusercontent.com/assets/197767/10712505/fe6267ac-7a9c-11e5-972e-2ace0fdd9523.png)
