### ISSUE TITLE
Cocoa pod spec update

### ISSUE THREAD

**Issue by james-ff** [fastred/AHKActionSheet#32]
Hello,

Would someone be able to update the cocoa pod spec for the repo?

I see that it hasn't been updated in 6 months, but other changes have been committed.
- As far as I am aware Cocoa pods users won't get these changes unless the spec version is progressed.

Cheers!

**Comment by lucasecf** [comment]
While you wait for the pod spec update, you can get the latest version of the code by adding the ```:head``` option to your Podfile:

```ruby
pod 'AHKActionSheet', :head
```

**Comment by fastred** [comment]
@james-ff Thanks for bringing this to my attention. I just released version [0.5.3](https://github.com/fastred/AHKActionSheet/releases/tag/0.5.3).

**Comment by james-ff** [comment]
Thanks guys!
