### ISSUE TITLE
Call back handler in swift 

### ISSUE THREAD

**Issue by karnakar** [fastred/AHKActionSheet#34]
Hi, closures are not working as expected 

actionSheet.addButtonWithTitle("Popularity",  type: AHKActionSheetButtonType.Default, handler: { (AHKActionSheet) in
   // do something
    })

**Comment by fastred** [comment]
Hi! What doesn't work as expected? Do they not compile?

**Comment by Coderlab** [comment]
Work for me:
actionSheet.addButtonWithTitle("Share", image: UIImage(named: "Icon3"), type: .Default, handler: {(AHKActionSheet) -> Void in
            NSLog("Share tapped")
        })
