### ISSUE TITLE
cancelOnTapEmptyAreaEnabled property is not used/does not work.

### ISSUE THREAD

**Issue by kAzec** [fastred/AHKActionSheet#35]
When I called `[actionSheet setCancelOnTapEmptyAreaEnabled:@(NO)];` before show it, the action sheet still responds to a tap gesture.

I found it is caused by the misuse of `cancelOnPanGestureEnabled` in [Here](https://github.com/fastred/AHKActionSheet/blob/master/Classes/AHKActionSheet.m#L278-L280)

Obviously the `cancelOnPanGestureEnabled` should actually be `cancelOnTapEmptyAreaEnabled`
Changing it fixed the issue:
```objective-c
if (self.cancelOnTapEmptyAreaEnabled.boolValue) {
        [self setUpCancelTapGestureForView:self.tableView];
    }
```

That's all, thanks for this great lib.

**Comment by fastred** [comment]
Thanks! I fixed this in https://github.com/fastred/AHKActionSheet/commit/19d4c2c629cbbbb90fe85c2584e463635b8b28ed :tada:
