### ISSUE TITLE
change color of image 

### ISSUE THREAD

**Issue by duelidave** [fastred/AHKActionSheet#36]
I am adding a Image to a button. The image should have another color as the text. 
How can i accomplish that? The image is surely in blue color. But is shown in white.

this is my image: 
`UIImage* maleImage = [UIImage imageNamed:@"male_icn_blue"];
        [maleImage imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];
        [maleImage drawInRect:CGRectMake(0, 0, 30, 30)];`

these are my color settings for the action Sheet: 
`actionSheet.buttonTextAttributes = @{ NSFontAttributeName : defaultFont,
                                              NSForegroundColorAttributeName : [UIColor whiteColor] };
        actionSheet.disabledButtonTextAttributes = @{ NSFontAttributeName : defaultFont,
                                                      NSForegroundColorAttributeName : [UIColor grayColor] };
        actionSheet.destructiveButtonTextAttributes = @{ NSFontAttributeName : defaultFont,
                                                         NSForegroundColorAttributeName : [UIColor redColor] };
        actionSheet.cancelButtonTextAttributes = @{ NSFontAttributeName : defaultFont,
                                                    NSForegroundColorAttributeName : [UIColor whiteColor] };`

I am adding the Image to the button like this: 
`[actionSheet addButtonWithTitle:MALE_STRING_DISPLAY
                                  image:maleImage
                                   type:AHKActionSheetButtonTypeDefault
                                handler:^(AHKActionSheet *as) {
                                    [[NSNotificationCenter defaultCenter] postNotificationName:@"enteredGenderCell"
                                                                                        object:MALE_STRING_DISPLAY
                                                                                      userInfo:nil];
                                }];`

How can i get the image in original color ?

**Comment by fastred** [comment]
You have to set [`automaticallyTintButtonImages`](https://github.com/fastred/AHKActionSheet/blob/master/Classes/AHKActionSheet.h#L44) property to `@NO`.

**Comment by duelidave** [comment]
Thanks! I appreciate your work! Good job.

**Comment by fastred** [comment]
Thanks for the nice words :smile:.
